language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install .
  - pip install python-numpy
  - pip install -r requirements.txt
# command to run test
script: python test_lactransformer.py